return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "clangd",
      "cmakelang",
      "cmakelint",
      "cpptools",
      "djlint",
      "flake8",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "neocmakelsp",
      "pyright",
      "ruff",
      "shellcheck",
      "sqlfluff",
      "stylua",
      "tree-sitter-cli",
      -- Formatters
      "autopep8",
      "black",
      "clang-format",
      "isort",
      "prettier",
      "shfmt",
      "xmlformatter",
      -- Linters / others
      "glsl_analyzer",
      "markdown-toc",
      "markdownlint-cli2",
    },
  },
}
